FROM ubuntu:focal
ARG DEBIAN_FRONTEND=noninteractive
RUN apt update && apt install -y curl libfuse2
ENV TOOLS_DIR="/tools"
RUN mkdir -p $TOOLS_DIR
ARG TARGETARCH
ARG ARCH
RUN if [ $TARGETARCH = amd64 ]; then \
      ARCH=x86_64; \
    elif [ $TARGETARCH = arm64 ]; then \
      ARCH=aarch64; \
    fi

RUN if [ ARCH=="x86_64" ]; then /bin/bash -c 'cd $TOOLS_DIR \
    && curl -LO https://github.com/linuxdeploy/linuxdeploy/releases/download/1-alpha-20231206-1/linuxdeploy-$ARCH.AppImage \
    && chmod +x linuxdeploy-$ARCH.AppImage \
    && ./linuxdeploy-$ARCH.AppImage --appimage-extract \
    && rm ./linuxdeploy-$ARCH.AppImage \
    && cd -'; fi

RUN apt -y upgrade && \
    apt install -y  \
        build-essential \
        git \
        libphysfs-dev \
        libsdl2-dev \
        libsdl2-mixer-dev \
        libsdl2-ttf-dev \
        python3  \
        python3-pip \
        python3-setuptools && \
    apt install -y  \
        wget && \
    rm -rf /var/lib/apt/lists && \
    python3 -m pip install meson ninja

RUN useradd -m npbuilder && passwd -d npbuilder

ENV DOCKER_NP_BUILD=TRUE

CMD ["/bin/bash","-l"]
