FROM ubuntu:jammy
ARG DEBIAN_FRONTEND=noninteractive
RUN apt update && apt upgrade -y && apt install -y \
        build-essential \
        gettext \
        git \
        liblua5.1-dev \
        libphysfs-dev \
        libsdl2-dev \
        libsdl2-mixer-dev \
        libsdl2-ttf-dev \
        meson \
        ninja-build \
        sudo

RUN useradd -m npbuilder && passwd -d npbuilder
RUN echo "npbuilder ALL=(ALL) ALL" >> /etc/sudoers

ENV DOCKER_NP_BUILD=TRUE

CMD ["/bin/bash","-l"]
