FROM ubuntu:jammy-20231128
ARG DEBIAN_FRONTEND=noninteractive
RUN apt update &&   \
    apt -y upgrade && \
    apt install -y  \
        build-essential \
        git \
        libphysfs-dev \
        libsdl2-dev \
        libsdl2-mixer-dev \
        libsdl2-ttf-dev \
        meson \
        python3  \
        python3-pip \
        python3-setuptools && \
    rm -rf /var/lib/apt/lists

RUN useradd -m npbuilder && passwd -d npbuilder

ENV DOCKER_NP_BUILD=TRUE

CMD ["/bin/bash","-l"]
