name: Format Check

on:
  push:
    branches: master
    paths:
    - 'src/**/**'
    - '**/check-formatting.yml'
  pull_request:
    branches: master
    paths:
    - 'src/**/**'
    - '**/check-formatting.yml'

jobs:
 clang-format-checking:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v4
     - uses: RafikFarhad/clang-format-github-action@v3
       with:
         sources: "src/**/*.cpp,src/**/*.hpp,src/**/*.c,src/**/*.h"
         style: Google
